// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/realname.proto

package realname

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Realname service

func NewRealnameEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Realname service

type RealnameService interface {
	AuthRealName(ctx context.Context, in *RealNameRequest, opts ...client.CallOption) (*RealNameResponse, error)
}

type realnameService struct {
	c    client.Client
	name string
}

func NewRealnameService(name string, c client.Client) RealnameService {
	return &realnameService{
		c:    c,
		name: name,
	}
}

func (c *realnameService) AuthRealName(ctx context.Context, in *RealNameRequest, opts ...client.CallOption) (*RealNameResponse, error) {
	req := c.c.NewRequest(c.name, "Realname.AuthRealName", in)
	out := new(RealNameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Realname service

type RealnameHandler interface {
	AuthRealName(context.Context, *RealNameRequest, *RealNameResponse) error
}

func RegisterRealnameHandler(s server.Server, hdlr RealnameHandler, opts ...server.HandlerOption) error {
	type realname interface {
		AuthRealName(ctx context.Context, in *RealNameRequest, out *RealNameResponse) error
	}
	type Realname struct {
		realname
	}
	h := &realnameHandler{hdlr}
	return s.Handle(s.NewHandler(&Realname{h}, opts...))
}

type realnameHandler struct {
	RealnameHandler
}

func (h *realnameHandler) AuthRealName(ctx context.Context, in *RealNameRequest, out *RealNameResponse) error {
	return h.RealnameHandler.AuthRealName(ctx, in, out)
}
