// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/reguser.proto

package reguser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Reguser service

func NewReguserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Reguser service

type ReguserService interface {
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
}

type reguserService struct {
	c    client.Client
	name string
}

func NewReguserService(name string, c client.Client) ReguserService {
	return &reguserService{
		c:    c,
		name: name,
	}
}

func (c *reguserService) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "Reguser.RegisterUser", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reguser service

type ReguserHandler interface {
	RegisterUser(context.Context, *RegisterRequest, *RegisterResponse) error
}

func RegisterReguserHandler(s server.Server, hdlr ReguserHandler, opts ...server.HandlerOption) error {
	type reguser interface {
		RegisterUser(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
	}
	type Reguser struct {
		reguser
	}
	h := &reguserHandler{hdlr}
	return s.Handle(s.NewHandler(&Reguser{h}, opts...))
}

type reguserHandler struct {
	ReguserHandler
}

func (h *reguserHandler) RegisterUser(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.ReguserHandler.RegisterUser(ctx, in, out)
}
